config/routes.rb
Rails.application.routes.draw do
  resources :songs, except: [:edit, :update, :destroy, :show]
  root 'songs#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/song.rb
class Song < ApplicationRecord

  validates :url, presence: true, format: { with: /\Ahttp(s?):\/\/music.yandex.ru\/(|album\/\d+\/)track\//}

  def embed_code
    audio = YandexMusic.new(self.url)
    audio.embed_code
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :verify_authenticity_token
end

app/controllers/songs_controller.rb
include Pagy::Backend

class SongsController < ApplicationController
  def index
    @pagy, @songs = pagy(Song.order(created_at: :desc))
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to root_url, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:url)
    end
end

app/helpers/application_helper.rb
 include Pagy::Frontend

module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice'  then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error'   then "alert alert-danger"
      when 'alert'   then "alert alert-danger"
    end
  end
end

app/views/application/_errors.html.haml
- if object.errors.any?
  #error_explanation
    %ul.alert.alert-warning
      - object.errors.full_messages.each do |msg|
        %li= msg

app/views/layouts/application.html.haml
!!!
%html(lang='ru')
  %head
    %meta(http-equiv='X-UA-Compatible' content='IE=Edge,chrome=1')
    %meta(name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no')
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Songs
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    = yield :js_header
  %body

    .container
      .row
        .col
          - flash.each do |key, value|
            %div{ class: flash_class(key) }= value

    = yield

app/views/songs/_form.html.haml
%section.fdb-block
  .container
    .row.justify-content-center
      .col.text-center
        = form_for(@song, html: { class: 'fdb-box fdb-touch' }) do |f|
          .row
            .col
              %h2= form_title
          = render 'application/errors', object: @song

          .row.mt-4
            .col
              = f.text_area :url, autofocus: true, autocomplete: "url", class: 'form-control', placeholder: "Song's yandex url (for example: https://music.yandex.ru/album/3152547/track/33332882)"

          .row.mt-4
            .col
              = f.submit 'Save', class: 'btn btn-secondary'
              = link_to 'Back', :back, class: 'btn btn-outline-secondary'

app/views/songs/_song.html.haml
%section.fdb-block.py-3
  .container
    .fdb-box
      .row.align-items-center.justify-content-center
        .col.ml-auto.mr-auto.mt-4.mt-md-0
          = raw song.embed_code

app/views/songs/index.html.haml
%section.fdb-block.yellow
  .container
    .row.align-items-center.justify-content-center
      .col-auto
        %h2 Add your favorite song
      .col-auto.mt-4.mt-sm-0
        = link_to 'New Song', new_song_path, class: 'btn btn-primary'

= render @songs

%section.fdb-block
  .container
    .row.align-items-center.justify-content-center
      .col-auto
        = raw pagy_bootstrap_nav(@pagy)

app/views/songs/new.html.haml
= render 'form', form_title: 'New song'